<?php
$definitions = array(
  'formnums' => array(
    'EXAMPLE' => '<p>This is an example. You can insert the Program or Phone number by using the <PROGRAM TITLE> or <PROGRAM PHONE> tokens.</p><p>Make sure you include any HTML tags and donn\'t forget to properly escape single quotes.</p>',
    '02896ANMENABC-ACS' => '<p>Being a healthy mom can be rewarding.</p><p>Enroll in the <PROGRAM TITLE> program and receive a customized Society onesie for your new little one!</p>',
    '02897ANMENABC-ACS' => '<p>Being a healthy mom can be rewarding.</p><p>Enroll in the <PROGRAM TITLE> program and receive a customized Society onesie for your new little one!</p>',
  ),
  'article_content' => 'This is the article content. Use the same tokens to insert title or phone. This is the name: <PROGRAM TITLE>, and this is the phone: <PROGRAM PHONE>',
  'program_name_block_content' => 'This is the program name block content. Use the same tokens.',
  'hw_articles' => array( // These are the nodes that the program block should show up on.
    '5298',
    '5295',
    '5296',
    '5294',
    '5300',
  ),
);
