<p>Earn up to $125 in Babies "R" Us gift cards for completing the <PROGRAM NAME> program*</p>

<p>Register and enroll in the <PROGRAM NAME> program during your first trimester to receive a $75 Babies "R" Us gift card. If you graduate from the <PROGRAM NAME> program completing the post-pregnancy assessment you will receive a $50 Babies "R" Us gift card. Call <PROGRAM NAME> at <PROGRAM PHONE>.</p>

<p>*Any Terex Corporation team member, spouse or same gender domestic partner who is covered by Anthem and completes the <PROGRAM NAME> program steps described above is eligible for this incentive.</p>
