<p><strong>Being a healthy mom can be rewarding</strong></p>

<p>Join <PROGRAM NAME> and get a copy of Your Pregnancy Week-by-Week at no extra charge to you! This best-selling book is filled with text and pictures that follow a mother and baby's journey through pregnancy. You'll also find exercise and nutrition tips, the latest product and safety information and guidance for dads-to-be. Enroll now by calling <PROGRAM PHONE>.</p>

