<p><strong>Qualify for this $300 value!</strong></p>
<p>Sign up for the <PROGRAM NAME> program and take advantage of this great deal. If you enroll in the program before 16 weeks of pregnancy and complete the program, you can be reimbursed for the cost of goods and services every mom needs, for up to $300. Items such as:<br />
<ul>
<li>Your copay for prenatal vitamins</li>
<li>Breast pumps, related supplies and lactation consultants</li>
<li>Tuition for birthing, parenting or infant-care classes</li>
<li>Pregnancy fitness classes</li>
<li>Postpartum wellness classes or a 6-month gym membership</li>
<li>Video classes if you're unable to attend classes in person</li>
<li>A jogging stroller</li>
</ul>

<p>Submit the claim form along with your receipts within 90 days of completing the program.</p>
