<p><strong>You can earn $225 by participating in <PROGRAM NAME>!</strong></p>
<p>Enrolling in <PROGRAM NAME> can help you have a healthy pregnancy. To earn a total of $225 you must:</p>
<ul>
<li>Enroll during your first trimester and complete your postpartum assessment.</li>
<li>We'll send you $75 when you enroll in your first trimester and $150 when you complete your postpartum assessment.</li>
</ul>
<p>Both rewards will be paid in your paycheck.</p>