<p><strong>Get rewarded!</strong></p>
<p>Members who complete the program receive a benefit credit that can be applied to a future medical claim on covered services for any eligible family member. The credit is applied toward deductibles and coinsurance. The credit amount depends on the semester in which you enroll in the <PROGRAM NAME> program.</p>
<ul>
<li>$250 credit issued if enrolled within the first trimester.</li>
<li>$200 credit issued if enrolled within the second trimester.</li>
<li>$150 credit issued if enrolled within the third trimester.</li>
</ul>
<p>Plus, get free prenatal vitamins during your pregnancy and for one year after delivery. Call today to start earning your rewards. The toll-free number is <PROGRAM PHONE>.</p>