<p><strong>Earn up to $200!*</strong></p>
<p>> Register for <PROGRAM NAME> and complete the initial assessment within your first trimester (16 weeks) and earn $100 toward your inpatient hospital copay.</p>
<p>> Complete a second assessment at your 20th week of pregnancy and earn an additional $100 toward your inpatient hospital copay.</p>
<p>Together, this will cover your inpatient copay for the delivery of your child! Call us toll-free at <PROGRAM PHONE> to register.</p>
<p>* Any Sage employee/spouse/partner who is covered by Anthem Blue Cross and Blue Shield and who completes the <PROGRAM NAME> program steps described above is eligible for these incentive payments.</p>