<p><strong>Reap even more rewards - $225</strong></p>
<p>In addition to the peace of mind you'll have from participating in <PROGRAM NAME>, you can earn up to two incentives worth a total of $225. Here's how:</p>
<ul>
<li>Register for <PROGRAM NAME> before your 12th week of pregnancy and receive a $150 Wellness Bonus* in your (or your spouse's) paycheck.</li>
<li>Register before your 12th week and complete the <PROGRAM NAME> postpartum assessment after you deliver to receive an additional $75 Wellness Bonus* in your (or your spouse's) paycheck.</li>
</ul>
<p>* Wellness Bonus is subject to applicable tax withholdings.</p>