<h1 class="title recipe-title text-color1"><PROGRAM NAME> is here for you!</h1>
<h2 class="dek">Get the support you need when you need it</h2>
<p>Having a baby means lots of excitement and anticipation&mdash;and also lots of questions. What foods are best to eat? What kind of exercise is safe? How often should you see a doctor? That's why there's <PROGRAM NAME>. It's a program that can help you prepare for a safe delivery and a healthy child. Best of all, it's no extra cost to you with your health plan. Sign up for <PROGRAM NAME> as soon as you find out your pregnant. Call <PROGRAM PHONE> to get started.</p>

<p><strong>How does <PROGRAM NAME> work?</strong></p>
<p>Every pregnancy is different, and with <PROGRAM NAME>, you'll get helpful information and support throughout your pregnancy. Our <PROGRAM NAME> nurse coaches get to know you and your family. They'll support you through the ups, downs, and surprises, be there to answer questions, and will celebrate the joy of a new baby with you.</p>

<p><strong>Here's what you'll get when you sign up:</strong></p>
<ul>
<li>A toll-free number you can use to talk to a nurse coach anytime, any day, about your pregnancy. Feel free to call us with questions that pop up in the middle of the night, too!</li>
<li>A maternity care diary packed with tips for a healthy pregnancy and space for you to keep track of doctor appointments as well as changes in your body and emotions throughout your pregnancy.</li>
<li>Your Pregnancy Week-by-Week, a book to show you what changes you can expect for you and your baby over the next nine months.</li>
<li>A health assessment to make sure you and your baby stay as healthy as possible.</li>
<li>Free phone calls with other specialists like dietitians, pharmacists, and social workers, as needed.</li>
<li>Other useful tools to help you, your doctor, and <Maternity Management> nurse keep track of your pregnancy and spot possible risks.</li>
</ul><br />

<p><strong>Sign up for <PROGRAM NAME> as soon as you find out you're pregnant. It's free for you.</strong></p>

<p><strong>Call <PROGRAM PHONE> to get started.</strong></p>
